# Generated by Django 2.1.2 on 2018-10-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='preview',
            field=models.CharField(default='None', max_length=70),
            preserve_default=False,
        ),
    ]
