# Generated by Django 2.1.2 on 2018-10-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='preview',
        ),
    ]
