# Generated by Django 2.1.2 on 2018-10-08 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='haItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.TextField()),
                ('information', models.TextField()),
                ('date_created_at', models.DateField(blank=True, default=datetime.date(2018, 10, 8))),
                ('date_until', models.DateField()),
            ],
            options={
                'verbose_name': 'haItem',
                'verbose_name_plural': 'haItems',
            },
        ),
    ]
