# Generated by Django 2.1.2 on 2018-10-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haitem',
            name='author',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
