# Generated by Django 2.1.2 on 2018-10-08 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0002_haitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haitem',
            name='date_created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
