# Generated by Django 2.1.2 on 2018-10-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0004_auto_20181008_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haitem',
            name='subject',
            field=models.CharField(choices=[('Bio', 'Biologie'), ('Ch', 'Chemie'), ('D', 'Deutsch'), ('E', 'Englisch'), ('eR', 'ev. Religion'), ('Ek', 'Erdkunde'), ('Fr', 'Französisch'), ('Ge', 'Geschichte'), ('Inf', 'Informatik'), ('kR', 'kath. Religion'), ('Ku', 'Kunst'), ('Lt', 'Latein'), ('M', 'Mathematik'), ('Ph', 'Philosophie'), ('Spo', 'Sport'), ('None', 'keins')], max_length=100),
        ),
    ]
