# Generated by Django 2.1.2 on 2018-10-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0005_auto_20181008_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haitem',
            options={'verbose_name': 'Hausaufgaben Eintrag', 'verbose_name_plural': 'Hausaufgaben Einträge'},
        ),
    ]
