# Generated by Django 2.1.2 on 2018-10-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0006_auto_20181008_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haitem',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
