# Generated by Django 2.1.2 on 2018-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0007_auto_20181008_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haitem',
            name='subject',
            field=models.CharField(choices=[('Biologie', 'Biologie'), ('Chemie', 'Chemie'), ('Deutsch', 'Deutsch'), ('Englisch', 'Englisch'), ('ev. Religion', 'ev. Religion'), ('Erdkunde', 'Erdkunde'), ('Französisch', 'Französisch'), ('Geschichte', 'Geschichte'), ('Informatik', 'Informatik'), ('kath. Religion', 'kath. Religion'), ('Kunst', 'Kunst'), ('Latein', 'Latein'), ('Mathematik', 'Mathematik'), ('Philosophie', 'Philosophie'), ('Sport', 'Sport'), ('keins', 'keins')], max_length=100),
        ),
    ]
