# Generated by Django 2.1.2 on 2018-10-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0008_auto_20181008_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='haitem',
            name='exercise_url',
            field=models.URLField(blank=True),
        ),
    ]
