# Generated by Django 2.1.2 on 2018-10-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0009_haitem_exercise_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haitem',
            old_name='exercise',
            new_name='aufgabe',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='exercise_url',
            new_name='aufgaben_url',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='date_until',
            new_name='bis',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='subject',
            new_name='fach',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='information',
            new_name='infos',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='date_created_at',
            new_name='von',
        ),
    ]
