# Generated by Django 2.1.2 on 2018-10-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0010_auto_20181015_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haitem',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='von',
            new_name='date_created_at',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='bis',
            new_name='date_until',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='aufgabe',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='aufgaben_url',
            new_name='exercise_url',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='infos',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='fach',
            new_name='subject',
        ),
    ]
